#!/usr/bin/env bash

# Set up autograder files

cp /autograder/submission/dt.py /autograder/source/dt.py
cp /autograder/submission/modelAssess.py /autograder/source/modelAssess.py

cd /autograder/source

python3 run_tests.py
